### ISSUE TITLE
pre-extracted (Jukebox) features from GDANCE music link is not provided

### ISSUE THREAD

**Issue by Da1yuqin** [aioz-ai/GCD#1]
Thanks for your great work! I found pre-extracted (Jukebox) features from GDANCE music is not provided, the link is lead to this git. Hope you can check this problem and provide the corresponding link, thanks!

**Comment by minhnhatvt** [comment]
Hi @Da1yuqin,

Sorry for the late reply, we have encountered some issues in processing and uploading the file previously. The download link is now ready in the readme.
